import React, { useState } from 'react'
import './Card.css'
 
/**
 * Template generated by Claude, enhanced by Anais Perron
 */

interface Recipe {
  id: number
  title: string
  description: string
  prepTime: number
  cookTime: number
  estimatedCost: number
  heroImage: string | null
  categories: string[],
}
 
const Card: React.FC<Recipe> = ({
  id,
  title,
  description,
  prepTime,
  cookTime,
  estimatedCost,
  heroImage,
  categories,
}) => {
  const [isFlipped, setIsFlipped] = useState(false)
 
  const handleFlip = (e: React.MouseEvent) => {
    e.stopPropagation()
    setIsFlipped(!isFlipped)
  }
 
  
 
  const renderStars = (rating: number) => {
    return Array.from({ length: 5 }, (_, i) => (
      <span key={i} className={`star ${i < rating ? 'filled' : 'empty'}`}>
        ★
      </span>
    ))
  }
 
  return (
    <div
      className={`recipe-flip-card ${isFlipped ? 'flipped' : ''}`}
      onClick={handleFlip}
    >
      <div className="recipe-flip-card-inner">
        {/* Front side */}
        <div className="recipe-flip-card-front">
          <div className="recipe-image-container">
              {heroImage && (
                    <div className="recipe-image">
                      <img
                        src={`http://localhost:3000/uploads/${heroImage}`}
                        alt={title}
                      />
                    </div>
                  )}
            <div className="recipe-image-overlay"></div>
          </div>
 
          <div className="recipe-content">
 
            <h2 className="recipe-title">{title}</h2>
 
            <div className="recipe-meta">
              <div className="meta-item">
                <span className="meta-icon">⏱️</span>
                <span className="meta-text">{prepTime + cookTime} mins</span>
              </div>
              <div className="meta-item">
                <span className="meta-icon">👥</span>
                <span className="meta-text">{categories.length} tags</span>
              </div>
              <div className="meta-item">
                <span className="meta-icon">📊</span>
                <span className="meta-text">{estimatedCost.toFixed(2)}</span>
              </div>
            </div>
                  {/* TODO: Implement handleFlip */}
            <button className="view-recipe-btn" onClick={handleFlip}>
              Choose
            </button>
          </div>
        </div>
 
        {/* Back side */}
        <div className="recipe-flip-card-back">
          <div className="recipe-back-content">
            <h3 className="back-title">Ingredients</h3>
 
          {/*  <ul className="ingredients-list">
              {ingredients.slice(0, 6).map((ingredient, index) => (
                <li key={index} className="ingredient-item">
                  <span className="ingredient-dot">•</span>
                  {ingredient}
                </li>
              ))}
            </ul>
 
            {ingredients.length > 6 && (
              <p className="ingredients-more">
                +{ingredients.length - 6} more ingredients
              </p>
            )}*/}
 
            {description && (
              <p className="recipe-description">{description}</p>
            )}
 
            <div className="back-footer">
              <p className="flip-hint">Click to flip back</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}
 
export default Card