export interface Ingredient {
  name: string;
  amount?: string;
  unit?: string;
}

export interface Recipe {
  id: number;
  createdBy?: number;
  title: string;
  description: string;
  prepTime: number;
  cookTime: number;
  difficulty: 'Easy' | 'Medium' | 'Hard';
  estimatedCost: number;
  heroImage: string | null;
  ingredients: (string | Ingredient)[];
  steps: string[];
  categories: string[];
  createdAt?: string;
  dietaryPreferences?: string[];
  allergies?: string[];
}

const fakeRecipes: Recipe[] = [
  {
    id: 1,
    title: 'Garlic Butter Pasta',
    description: 'Spaghetti tossed in garlic-infused butter with parmesan and fresh parsley.',
    prepTime: 5,
    cookTime: 15,
    difficulty: 'Easy',
    estimatedCost: 4.5,
    heroImage: null,
    categories: ['quick', 'vegetarian', 'easy'],
    dietaryPreferences: ['vegetarian'],
    allergies: ['wheat', 'milk'],
    ingredients: [
      { name: 'spaghetti', amount: '200', unit: 'g' },
      { name: 'garlic', amount: '3', unit: 'cloves' },
      { name: 'butter', amount: '40', unit: 'g' },
      { name: 'parmesan', amount: '50', unit: 'g' },
      { name: 'parsley', amount: '1', unit: 'tbsp' },
    ],
    steps: [
      'Cook spaghetti in salted boiling water until al dente.',
      'Melt butter in a large pan over medium heat.',
      'Add minced garlic and cook for 1–2 minutes until fragrant.',
      'Drain pasta, reserving ½ cup pasta water.',
      'Toss pasta in the garlic butter, adding pasta water to loosen.',
      'Serve topped with grated parmesan and fresh parsley.',
    ],
  },
  {
    id: 2,
    title: 'Classic Tomato Soup',
    description: 'Creamy blended tomato soup with garlic, onion, and a touch of cream.',
    prepTime: 10,
    cookTime: 25,
    difficulty: 'Easy',
    estimatedCost: 3.0,
    heroImage: null,
    categories: ['vegetarian', 'comfort', 'easy'],
    dietaryPreferences: ['vegetarian'],
    allergies: ['milk'],
    ingredients: [
      { name: 'canned tomatoes', amount: '800', unit: 'g' },
      { name: 'garlic', amount: '2', unit: 'cloves' },
      { name: 'onion', amount: '1', unit: 'unit' },
      { name: 'cream', amount: '60', unit: 'ml' },
      { name: 'olive oil', amount: '2', unit: 'tbsp' },
    ],
    steps: [
      'Sauté diced onion and garlic in olive oil until soft.',
      'Add canned tomatoes and 400 ml water.',
      'Simmer for 20 minutes.',
      'Blend until smooth.',
      'Stir in cream, season with salt and pepper, and serve.',
    ],
  },
  {
    id: 3,
    title: 'Scrambled Eggs & Toast',
    description: 'Fluffy scrambled eggs with butter on toasted white bread.',
    prepTime: 2,
    cookTime: 5,
    difficulty: 'Easy',
    estimatedCost: 2.0,
    heroImage: null,
    categories: ['breakfast', 'quick', 'easy'],
    dietaryPreferences: ['vegetarian'],
    allergies: ['eggs', 'wheat', 'milk'],
    ingredients: [
      { name: 'eggs', amount: '3', unit: 'unit' },
      { name: 'butter', amount: '15', unit: 'g' },
      { name: 'bread', amount: '2', unit: 'slices' },
    ],
    steps: [
      'Whisk eggs with a pinch of salt.',
      'Melt butter in a non-stick pan over low heat.',
      'Add eggs and stir gently until just set.',
      'Toast bread and serve eggs on top.',
    ],
  },
  {
    id: 4,
    title: 'Chicken Fried Rice',
    description: 'Day-old rice stir-fried with chicken, egg, soy sauce, and scallions.',
    prepTime: 10,
    cookTime: 15,
    difficulty: 'Medium',
    estimatedCost: 5.5,
    heroImage: null,
    categories: ['quick', 'high-protein', 'dairy-free'],
    dietaryPreferences: [],
    allergies: ['eggs', 'soy'],
    ingredients: [
      { name: 'cooked rice', amount: '300', unit: 'g' },
      { name: 'chicken breast', amount: '150', unit: 'g' },
      { name: 'eggs', amount: '2', unit: 'unit' },
      { name: 'soy sauce', amount: '2', unit: 'tbsp' },
      { name: 'scallions', amount: '3', unit: 'unit' },
      { name: 'sesame oil', amount: '1', unit: 'tsp' },
    ],
    steps: [
      'Dice chicken and stir-fry in a hot wok with oil until cooked.',
      'Push chicken to one side and scramble the eggs.',
      'Add cold rice and break up any clumps.',
      'Add soy sauce and sesame oil, toss everything together.',
      'Garnish with sliced scallions and serve.',
    ],
  },
  {
    id: 5,
    title: 'Onion & Cheese Omelette',
    description: 'Three-egg omelette filled with sautéed onion and melted cheddar cheese.',
    prepTime: 5,
    cookTime: 8,
    difficulty: 'Easy',
    estimatedCost: 2.5,
    heroImage: null,
    categories: ['breakfast', 'vegetarian', 'quick'],
    dietaryPreferences: ['vegetarian'],
    allergies: ['eggs', 'milk'],
    ingredients: [
      { name: 'eggs', amount: '3', unit: 'unit' },
      { name: 'onion', amount: '½', unit: 'unit' },
      { name: 'cheddar', amount: '40', unit: 'g' },
      { name: 'butter', amount: '10', unit: 'g' },
    ],
    steps: [
      'Sauté diced onion in butter until golden.',
      'Whisk eggs with salt and pepper.',
      'Pour eggs into the pan over the onion.',
      'When edges set, add grated cheddar and fold the omelette.',
      'Serve immediately.',
    ],
  },
  {
    id: 6,
    title: 'Lemon Herb Chicken',
    description: 'Oven-baked chicken thighs marinated in lemon juice, garlic, and herbs.',
    prepTime: 10,
    cookTime: 35,
    difficulty: 'Easy',
    estimatedCost: 7.0,
    heroImage: null,
    categories: ['high-protein', 'dairy-free', 'gluten-free'],
    dietaryPreferences: ['gluten-free', 'dairy-free'],
    allergies: [],
    ingredients: [
      { name: 'chicken thighs', amount: '4', unit: 'unit' },
      { name: 'lemon', amount: '1', unit: 'unit' },
      { name: 'garlic', amount: '3', unit: 'cloves' },
      { name: 'herbs (thyme, rosemary)', amount: '1', unit: 'tbsp' },
      { name: 'olive oil', amount: '3', unit: 'tbsp' },
    ],
    steps: [
      'Mix lemon juice, minced garlic, herbs, and olive oil.',
      'Marinate chicken for at least 20 minutes.',
      'Preheat oven to 200°C.',
      'Place chicken in a baking dish and roast 35 minutes until golden.',
      'Rest 5 minutes before serving.',
    ],
  },
  {
    id: 7,
    title: 'Potato Leek Soup',
    description: 'Smooth and comforting soup made with potatoes, leeks, and vegetable broth.',
    prepTime: 10,
    cookTime: 30,
    difficulty: 'Easy',
    estimatedCost: 4.0,
    heroImage: null,
    categories: ['vegetarian', 'comfort', 'gluten-free'],
    dietaryPreferences: ['vegetarian', 'gluten-free'],
    allergies: ['milk'],
    ingredients: [
      { name: 'potatoes', amount: '4', unit: 'unit' },
      { name: 'leeks', amount: '2', unit: 'unit' },
      { name: 'butter', amount: '30', unit: 'g' },
      { name: 'onion', amount: '1', unit: 'unit' },
      { name: 'vegetable broth', amount: '800', unit: 'ml' },
    ],
    steps: [
      'Slice leeks and dice onion.',
      'Sweat leeks and onion in butter for 5 minutes.',
      'Peel and cube potatoes, add to pot with broth.',
      'Simmer 25 minutes until potatoes are tender.',
      'Blend until smooth, season, and serve.',
    ],
  },
  {
    id: 8,
    title: 'Tuna Pasta Salad',
    description: 'Chilled pasta with canned tuna, mayo, celery, and a squeeze of lemon.',
    prepTime: 10,
    cookTime: 10,
    difficulty: 'Easy',
    estimatedCost: 4.0,
    heroImage: null,
    categories: ['quick', 'budget-friendly', 'high-protein'],
    dietaryPreferences: [],
    allergies: ['wheat', 'fish', 'eggs'],
    ingredients: [
      { name: 'pasta', amount: '200', unit: 'g' },
      { name: 'canned tuna', amount: '160', unit: 'g' },
      { name: 'mayo', amount: '3', unit: 'tbsp' },
      { name: 'celery', amount: '2', unit: 'stalks' },
      { name: 'lemon juice', amount: '1', unit: 'tbsp' },
    ],
    steps: [
      'Cook pasta, drain, and cool under cold water.',
      'Drain tuna and flake into a bowl.',
      'Dice celery and mix with tuna, mayo, and lemon juice.',
      'Combine with pasta, season, and refrigerate until serving.',
    ],
  },
  {
    id: 9,
    title: 'Black Bean Tacos',
    description: 'Corn tortillas filled with seasoned black beans, salsa, and shredded cabbage.',
    prepTime: 10,
    cookTime: 10,
    difficulty: 'Easy',
    estimatedCost: 3.5,
    heroImage: null,
    categories: ['vegan', 'quick', 'budget-friendly'],
    dietaryPreferences: ['vegan', 'gluten-free'],
    allergies: [],
    ingredients: [
      { name: 'black beans', amount: '400', unit: 'g' },
      { name: 'corn tortillas', amount: '6', unit: 'unit' },
      { name: 'salsa', amount: '4', unit: 'tbsp' },
      { name: 'cabbage', amount: '1', unit: 'cup' },
      { name: 'cumin', amount: '1', unit: 'tsp' },
      { name: 'lime', amount: '1', unit: 'unit' },
    ],
    steps: [
      'Drain and rinse beans, warm in a pan with cumin and salt.',
      'Shred cabbage thinly.',
      'Warm tortillas on a dry pan.',
      'Fill each tortilla with beans, cabbage, and salsa.',
      'Squeeze lime on top and serve.',
    ],
  },
  {
    id: 10,
    title: 'Vegetable Stir-Fry',
    description: 'Broccoli, carrots, and bell pepper stir-fried in soy sauce and sesame oil.',
    prepTime: 10,
    cookTime: 10,
    difficulty: 'Easy',
    estimatedCost: 4.5,
    heroImage: null,
    categories: ['vegan', 'quick', 'healthy'],
    dietaryPreferences: ['vegan', 'dairy-free'],
    allergies: ['soy', 'sesame'],
    ingredients: [
      { name: 'broccoli', amount: '200', unit: 'g' },
      { name: 'carrots', amount: '2', unit: 'unit' },
      { name: 'bell pepper', amount: '1', unit: 'unit' },
      { name: 'soy sauce', amount: '2', unit: 'tbsp' },
      { name: 'sesame oil', amount: '1', unit: 'tsp' },
      { name: 'garlic', amount: '2', unit: 'cloves' },
    ],
    steps: [
      'Cut all vegetables into bite-sized pieces.',
      'Heat oil in a wok over high heat.',
      'Stir-fry garlic 30 seconds, then add vegetables.',
      'Cook 5–7 minutes, tossing frequently.',
      'Add soy sauce and sesame oil, toss, and serve.',
    ],
  },
  {
    id: 11,
    title: 'Avocado Toast',
    description: 'Mashed avocado on toasted sourdough with lemon, salt, and chili flakes.',
    prepTime: 5,
    cookTime: 3,
    difficulty: 'Easy',
    estimatedCost: 3.5,
    heroImage: null,
    categories: ['breakfast', 'vegan', 'quick'],
    dietaryPreferences: ['vegan'],
    allergies: ['wheat'],
    ingredients: [
      { name: 'avocado', amount: '1', unit: 'unit' },
      { name: 'sourdough bread', amount: '2', unit: 'slices' },
      { name: 'lemon juice', amount: '1', unit: 'tsp' },
      { name: 'chili flakes', amount: '1', unit: 'pinch' },
    ],
    steps: [
      'Toast the sourdough slices.',
      'Mash avocado with lemon juice, salt, and pepper.',
      'Spread avocado on toast.',
      'Top with chili flakes and serve.',
    ],
  },
  {
    id: 12,
    title: 'Beef & Potato Stew',
    description: 'Slow-cooked beef chunks with potatoes, carrots, and tomato in a rich broth.',
    prepTime: 15,
    cookTime: 90,
    difficulty: 'Medium',
    estimatedCost: 9.0,
    heroImage: null,
    categories: ['comfort', 'high-protein', 'dairy-free'],
    dietaryPreferences: ['dairy-free', 'gluten-free'],
    allergies: [],
    ingredients: [
      { name: 'beef chuck', amount: '500', unit: 'g' },
      { name: 'potatoes', amount: '3', unit: 'unit' },
      { name: 'carrots', amount: '2', unit: 'unit' },
      { name: 'canned tomatoes', amount: '400', unit: 'g' },
      { name: 'onion', amount: '1', unit: 'unit' },
      { name: 'beef broth', amount: '500', unit: 'ml' },
    ],
    steps: [
      'Cut beef into 3 cm chunks, season with salt and pepper.',
      'Brown beef in batches in a heavy pot over high heat.',
      'Sauté onion, then add tomatoes and broth.',
      'Return beef, add diced potatoes and carrots.',
      'Simmer 1.5 hours until beef is tender.',
      'Adjust seasoning and serve.',
    ],
  },
  {
    id: 13,
    title: 'Caprese Salad',
    description: 'Fresh mozzarella, tomato, and basil drizzled with olive oil and balsamic glaze.',
    prepTime: 5,
    cookTime: 0,
    difficulty: 'Easy',
    estimatedCost: 5.0,
    heroImage: null,
    categories: ['vegetarian', 'no-cook', 'easy'],
    dietaryPreferences: ['vegetarian', 'gluten-free'],
    allergies: ['milk'],
    ingredients: [
      { name: 'fresh mozzarella', amount: '200', unit: 'g' },
      { name: 'tomatoes', amount: '3', unit: 'unit' },
      { name: 'fresh basil', amount: '10', unit: 'leaves' },
      { name: 'olive oil', amount: '2', unit: 'tbsp' },
      { name: 'balsamic glaze', amount: '1', unit: 'tbsp' },
    ],
    steps: [
      'Slice mozzarella and tomatoes into equal rounds.',
      'Alternate slices on a plate.',
      'Tuck basil leaves between slices.',
      'Drizzle with olive oil and balsamic glaze.',
      'Season with salt and serve immediately.',
    ],
  },
  {
    id: 14,
    title: 'French Onion Soup',
    description: 'Caramelized onion soup topped with a crouton and melted gruyère cheese.',
    prepTime: 10,
    cookTime: 50,
    difficulty: 'Medium',
    estimatedCost: 6.0,
    heroImage: null,
    categories: ['comfort', 'vegetarian'],
    dietaryPreferences: ['vegetarian'],
    allergies: ['wheat', 'milk'],
    ingredients: [
      { name: 'onions', amount: '4', unit: 'unit' },
      { name: 'butter', amount: '40', unit: 'g' },
      { name: 'baguette slices', amount: '2', unit: 'unit' },
      { name: 'gruyère', amount: '80', unit: 'g' },
      { name: 'beef broth', amount: '800', unit: 'ml' },
      { name: 'white wine', amount: '100', unit: 'ml' },
    ],
    steps: [
      'Slice onions thinly and caramelize in butter over low heat, 40 minutes.',
      'Add white wine and reduce by half.',
      'Add broth, simmer 10 minutes, and season.',
      'Ladle into oven-safe bowls, top with baguette slices and cheese.',
      'Broil until cheese is bubbly and golden.',
    ],
  },
  {
    id: 15,
    title: 'Pancakes',
    description: 'Fluffy pancakes made with flour, eggs, milk, and butter. Serve with maple syrup.',
    prepTime: 5,
    cookTime: 15,
    difficulty: 'Easy',
    estimatedCost: 2.5,
    heroImage: null,
    categories: ['breakfast', 'vegetarian', 'easy'],
    dietaryPreferences: ['vegetarian'],
    allergies: ['wheat', 'eggs', 'milk'],
    ingredients: [
      { name: 'flour', amount: '150', unit: 'g' },
      { name: 'eggs', amount: '2', unit: 'unit' },
      { name: 'milk', amount: '200', unit: 'ml' },
      { name: 'butter', amount: '20', unit: 'g' },
      { name: 'baking powder', amount: '1', unit: 'tsp' },
      { name: 'maple syrup', amount: '2', unit: 'tbsp' },
    ],
    steps: [
      'Mix flour and baking powder in a bowl.',
      'Whisk eggs, milk, and melted butter together.',
      'Combine wet and dry ingredients until just mixed.',
      'Cook spoonfuls on a buttered pan over medium heat.',
      'Flip when bubbles appear. Serve with maple syrup.',
    ],
  },
  {
    id: 16,
    title: 'Greek Salad',
    description:
      'Cucumber, tomato, red onion, olives, and feta cheese dressed in olive oil and oregano.',
    prepTime: 10,
    cookTime: 0,
    difficulty: 'Easy',
    estimatedCost: 5.5,
    heroImage: null,
    categories: ['vegetarian', 'no-cook', 'healthy', 'gluten-free'],
    dietaryPreferences: ['vegetarian', 'gluten-free'],
    allergies: ['milk'],
    ingredients: [
      { name: 'cucumber', amount: '1', unit: 'unit' },
      { name: 'tomatoes', amount: '3', unit: 'unit' },
      { name: 'red onion', amount: '½', unit: 'unit' },
      { name: 'kalamata olives', amount: '80', unit: 'g' },
      { name: 'feta cheese', amount: '100', unit: 'g' },
      { name: 'olive oil', amount: '3', unit: 'tbsp' },
      { name: 'dried oregano', amount: '1', unit: 'tsp' },
    ],
    steps: [
      'Chop cucumber, tomatoes, and red onion into chunks.',
      'Combine in a large bowl with olives.',
      'Top with crumbled feta.',
      'Drizzle with olive oil and sprinkle oregano.',
      'Toss lightly and serve.',
    ],
  },
  {
    id: 17,
    title: 'Tomato Basil Bruschetta',
    description: 'Toasted baguette slices topped with diced tomato, garlic, and fresh basil.',
    prepTime: 10,
    cookTime: 5,
    difficulty: 'Easy',
    estimatedCost: 3.0,
    heroImage: null,
    categories: ['vegetarian', 'quick', 'easy'],
    dietaryPreferences: ['vegan'],
    allergies: ['wheat'],
    ingredients: [
      { name: 'baguette', amount: '½', unit: 'unit' },
      { name: 'tomatoes', amount: '3', unit: 'unit' },
      { name: 'garlic', amount: '1', unit: 'clove' },
      { name: 'fresh basil', amount: '8', unit: 'leaves' },
      { name: 'olive oil', amount: '2', unit: 'tbsp' },
    ],
    steps: [
      'Slice and toast baguette under a broiler.',
      'Rub toasted slices with a cut garlic clove.',
      'Dice tomatoes and mix with chopped basil and olive oil.',
      'Spoon tomato mixture onto bread and serve.',
    ],
  },
  {
    id: 18,
    title: 'Spaghetti Bolognese',
    description: 'Ground beef slow-simmered with tomato, onion, garlic, and red wine over pasta.',
    prepTime: 10,
    cookTime: 40,
    difficulty: 'Medium',
    estimatedCost: 8.0,
    heroImage: null,
    categories: ['comfort', 'high-protein'],
    dietaryPreferences: ['dairy-free'],
    allergies: ['wheat'],
    ingredients: [
      { name: 'spaghetti', amount: '200', unit: 'g' },
      { name: 'ground beef', amount: '300', unit: 'g' },
      { name: 'canned tomatoes', amount: '400', unit: 'g' },
      { name: 'onion', amount: '1', unit: 'unit' },
      { name: 'garlic', amount: '2', unit: 'cloves' },
      { name: 'red wine', amount: '100', unit: 'ml' },
    ],
    steps: [
      'Sauté diced onion and garlic in olive oil.',
      'Brown ground beef until no pink remains.',
      'Add red wine and reduce by half.',
      'Add canned tomatoes, simmer 30 minutes.',
      'Cook spaghetti, toss with sauce, and serve.',
    ],
  },
  {
    id: 19,
    title: 'Banana Oat Smoothie',
    description: 'Blended banana, rolled oats, milk, and honey for a filling breakfast drink.',
    prepTime: 5,
    cookTime: 0,
    difficulty: 'Easy',
    estimatedCost: 2.0,
    heroImage: null,
    categories: ['breakfast', 'vegetarian', 'no-cook', 'quick'],
    dietaryPreferences: ['vegetarian'],
    allergies: ['milk', 'gluten'],
    ingredients: [
      { name: 'banana', amount: '1', unit: 'unit' },
      { name: 'rolled oats', amount: '40', unit: 'g' },
      { name: 'milk', amount: '250', unit: 'ml' },
      { name: 'honey', amount: '1', unit: 'tbsp' },
    ],
    steps: [
      'Add all ingredients to a blender.',
      'Blend until smooth.',
      'Pour into a glass and serve immediately.',
    ],
  },
  {
    id: 20,
    title: 'Baked Salmon',
    description: 'Salmon fillet baked with lemon slices, garlic, and olive oil until flaky.',
    prepTime: 5,
    cookTime: 20,
    difficulty: 'Easy',
    estimatedCost: 8.5,
    heroImage: null,
    categories: ['high-protein', 'gluten-free', 'healthy', 'fish'],
    dietaryPreferences: ['gluten-free', 'dairy-free'],
    allergies: ['fish'],
    ingredients: [
      { name: 'salmon fillet', amount: '2', unit: 'unit' },
      { name: 'lemon', amount: '1', unit: 'unit' },
      { name: 'garlic', amount: '2', unit: 'cloves' },
      { name: 'olive oil', amount: '2', unit: 'tbsp' },
      { name: 'fresh dill', amount: '1', unit: 'tbsp' },
    ],
    steps: [
      'Preheat oven to 200°C.',
      'Place salmon in a baking dish.',
      'Top with lemon slices, minced garlic, olive oil, and dill.',
      'Bake 15–18 minutes until salmon flakes easily.',
      'Serve with a lemon wedge.',
    ],
  },
  {
    id: 21,
    title: 'Cheese Quesadillas',
    description: 'Flour tortillas filled with melted cheddar cheese, grilled until crispy.',
    prepTime: 3,
    cookTime: 7,
    difficulty: 'Easy',
    estimatedCost: 2.5,
    heroImage: null,
    categories: ['vegetarian', 'quick', 'easy'],
    dietaryPreferences: ['vegetarian'],
    allergies: ['wheat', 'milk'],
    ingredients: [
      { name: 'flour tortillas', amount: '2', unit: 'unit' },
      { name: 'cheddar cheese', amount: '80', unit: 'g' },
      { name: 'butter', amount: '10', unit: 'g' },
    ],
    steps: [
      'Grate cheddar and spread over one tortilla.',
      'Place second tortilla on top.',
      'Cook in a buttered pan over medium heat 3 minutes per side.',
      'Cut into wedges and serve with salsa or sour cream.',
    ],
  },
  {
    id: 22,
    title: 'Lentil Soup',
    description: 'Hearty red lentil soup with cumin, tomato, onion, and a squeeze of lemon.',
    prepTime: 10,
    cookTime: 30,
    difficulty: 'Easy',
    estimatedCost: 3.5,
    heroImage: null,
    categories: ['vegan', 'budget-friendly', 'healthy', 'gluten-free'],
    dietaryPreferences: ['vegan', 'gluten-free'],
    allergies: [],
    ingredients: [
      { name: 'red lentils', amount: '200', unit: 'g' },
      { name: 'onion', amount: '1', unit: 'unit' },
      { name: 'canned tomatoes', amount: '400', unit: 'g' },
      { name: 'cumin', amount: '1', unit: 'tsp' },
      { name: 'lemon juice', amount: '2', unit: 'tbsp' },
      { name: 'vegetable broth', amount: '800', unit: 'ml' },
    ],
    steps: [
      'Sauté diced onion in olive oil with cumin.',
      'Add rinsed lentils, tomatoes, and broth.',
      'Simmer 25 minutes until lentils are soft.',
      'Blend partially for a creamy texture.',
      'Stir in lemon juice, season, and serve.',
    ],
  },
  {
    id: 23,
    title: 'Caesar Salad',
    description: 'Romaine lettuce with parmesan, croutons, and classic Caesar dressing.',
    prepTime: 10,
    cookTime: 0,
    difficulty: 'Easy',
    estimatedCost: 5.0,
    heroImage: null,
    categories: ['vegetarian', 'no-cook', 'easy'],
    dietaryPreferences: ['vegetarian'],
    allergies: ['wheat', 'eggs', 'fish', 'milk'],
    ingredients: [
      { name: 'romaine lettuce', amount: '1', unit: 'head' },
      { name: 'parmesan', amount: '40', unit: 'g' },
      { name: 'croutons', amount: '40', unit: 'g' },
      { name: 'Caesar dressing', amount: '4', unit: 'tbsp' },
    ],
    steps: [
      'Tear romaine into pieces and place in a large bowl.',
      'Add Caesar dressing and toss to coat.',
      'Top with parmesan shavings and croutons.',
      'Serve immediately.',
    ],
  },
  {
    id: 24,
    title: 'Beef Tacos',
    description:
      'Ground beef seasoned with cumin and chili powder in corn tortillas with toppings.',
    prepTime: 10,
    cookTime: 15,
    difficulty: 'Easy',
    estimatedCost: 7.0,
    heroImage: null,
    categories: ['quick', 'high-protein'],
    dietaryPreferences: ['dairy-free', 'gluten-free'],
    allergies: [],
    ingredients: [
      { name: 'ground beef', amount: '300', unit: 'g' },
      { name: 'corn tortillas', amount: '6', unit: 'unit' },
      { name: 'cumin', amount: '1', unit: 'tsp' },
      { name: 'chili powder', amount: '1', unit: 'tsp' },
      { name: 'onion', amount: '½', unit: 'unit' },
      { name: 'salsa', amount: '4', unit: 'tbsp' },
    ],
    steps: [
      'Brown ground beef in a pan, breaking it up.',
      'Add cumin, chili powder, and diced onion.',
      'Cook until onion softens, about 5 minutes.',
      'Warm tortillas on a dry pan.',
      'Fill with beef and top with salsa.',
    ],
  },
  {
    id: 25,
    title: 'Mushroom Risotto',
    description: 'Creamy arborio rice cooked with mushrooms, white wine, garlic, and parmesan.',
    prepTime: 10,
    cookTime: 35,
    difficulty: 'Hard',
    estimatedCost: 7.5,
    heroImage: null,
    categories: ['vegetarian', 'comfort'],
    dietaryPreferences: ['vegetarian', 'gluten-free'],
    allergies: ['milk'],
    ingredients: [
      { name: 'arborio rice', amount: '300', unit: 'g' },
      { name: 'mushrooms', amount: '250', unit: 'g' },
      { name: 'garlic', amount: '2', unit: 'cloves' },
      { name: 'parmesan', amount: '60', unit: 'g' },
      { name: 'butter', amount: '40', unit: 'g' },
      { name: 'white wine', amount: '100', unit: 'ml' },
      { name: 'vegetable broth', amount: '1', unit: 'l' },
    ],
    steps: [
      'Sauté garlic and mushrooms in butter until golden.',
      'Add arborio rice and toast 1 minute.',
      'Pour in white wine and stir until absorbed.',
      'Add warm broth one ladle at a time, stirring constantly.',
      'After 25–30 minutes, rice should be creamy.',
      'Stir in parmesan, season, and serve.',
    ],
  },
];

export default fakeRecipes;
