interface Recipe {
  id: number
  title: string
  description: string
  prepTime: number
  cookTime: number
  estimatedCost: number
  heroImage: string | null
  categories: string[]
  ingredients: string[]
}

const fakeRecipes: Recipe[] = [
  {
    id: 1,
    title: 'Garlic Butter Pasta',
    description: 'Spaghetti tossed in garlic-infused butter with parmesan and fresh parsley.',
    prepTime: 5,
    cookTime: 15,
    estimatedCost: 4.5,
    heroImage: null,
    categories: ['quick', 'vegetarian', 'easy'],
    ingredients: ['pasta', 'garlic', 'butter', 'parmesan', 'parsley'],
  },
  {
    id: 2,
    title: 'Classic Tomato Soup',
    description: 'Creamy blended tomato soup with garlic, onion, and a touch of cream.',
    prepTime: 10,
    cookTime: 25,
    estimatedCost: 3.0,
    heroImage: null,
    categories: ['vegetarian', 'comfort', 'easy'],
    ingredients: ['tomato', 'garlic', 'onion', 'cream'],
  },
  {
    id: 3,
    title: 'Scrambled Eggs & Toast',
    description: 'Fluffy scrambled eggs with butter on toasted white bread.',
    prepTime: 2,
    cookTime: 5,
    estimatedCost: 2.0,
    heroImage: null,
    categories: ['breakfast', 'quick', 'easy'],
    ingredients: ['eggs', 'butter', 'bread'],
  },
  {
    id: 4,
    title: 'Chicken Fried Rice',
    description: 'Day-old rice stir-fried with chicken, egg, soy sauce, and scallions.',
    prepTime: 10,
    cookTime: 15,
    estimatedCost: 5.5,
    heroImage: null,
    categories: ['quick', 'high-protein', 'dairy-free'],
    ingredients: ['chicken', 'rice', 'eggs', 'soy sauce', 'scallions'],
  },
  {
    id: 5,
    title: 'Onion & Cheese Omelette',
    description: 'Three-egg omelette filled with sautéed onion and melted cheddar cheese.',
    prepTime: 5,
    cookTime: 8,
    estimatedCost: 2.5,
    heroImage: null,
    categories: ['breakfast', 'vegetarian', 'quick'],
    ingredients: ['eggs', 'onion', 'cheddar'],
  },
  {
    id: 6,
    title: 'Lemon Herb Chicken',
    description: 'Oven-baked chicken thighs marinated in lemon juice, garlic, and herbs.',
    prepTime: 10,
    cookTime: 35,
    estimatedCost: 7.0,
    heroImage: null,
    categories: ['high-protein', 'dairy-free', 'gluten-free'],
    ingredients: ['chicken', 'lemon', 'garlic', 'herbs', 'olive oil'],
  },
  {
    id: 7,
    title: 'Potato Leek Soup',
    description: 'Smooth and comforting soup made with potatoes, leeks, and vegetable broth.',
    prepTime: 10,
    cookTime: 30,
    estimatedCost: 4.0,
    heroImage: null,
    categories: ['vegetarian', 'comfort', 'gluten-free'],
    ingredients: ['potatoes', 'leeks', 'butter', 'onion'],
  },
  {
    id: 8,
    title: 'Tuna Pasta Salad',
    description: 'Chilled pasta with canned tuna, mayo, celery, and a squeeze of lemon.',
    prepTime: 10,
    cookTime: 10,
    estimatedCost: 4.0,
    heroImage: null,
    categories: ['quick', 'budget-friendly', 'high-protein'],
    ingredients: ['pasta', 'tuna', 'mayo', 'celery', 'lemon'],
  },
  {
    id: 9,
    title: 'Black Bean Tacos',
    description: 'Corn tortillas filled with seasoned black beans, salsa, and shredded cabbage.',
    prepTime: 10,
    cookTime: 10,
    estimatedCost: 3.5,
    heroImage: null,
    categories: ['vegan', 'quick', 'budget-friendly'],
    ingredients: ['black beans', 'tortillas', 'salsa', 'cabbage'],
  },
  {
    id: 10,
    title: 'Vegetable Stir-Fry',
    description: 'Broccoli, carrots, and bell pepper stir-fried in soy sauce and sesame oil.',
    prepTime: 10,
    cookTime: 10,
    estimatedCost: 4.5,
    heroImage: null,
    categories: ['vegan', 'quick', 'healthy', 'soy', 'sesame'],
    ingredients: ['broccoli', 'carrots', 'bell pepper', 'soy sauce', 'sesame oil'],
  },
  {
    id: 11,
    title: 'Avocado Toast',
    description: 'Mashed avocado on toasted sourdough with lemon, salt, and chili flakes.',
    prepTime: 5,
    cookTime: 3,
    estimatedCost: 3.5,
    heroImage: null,
    categories: ['breakfast', 'vegan', 'quick'],
    ingredients: ['avocado', 'bread', 'lemon'],
  },
  {
    id: 12,
    title: 'Beef & Potato Stew',
    description: 'Slow-cooked beef chunks with potatoes, carrots, and tomato in a rich broth.',
    prepTime: 15,
    cookTime: 90,
    estimatedCost: 9.0,
    heroImage: null,
    categories: ['comfort', 'high-protein', 'dairy-free'],
    ingredients: ['beef', 'potatoes', 'carrots', 'tomato', 'onion'],
  },
  {
    id: 13,
    title: 'Caprese Salad',
    description: 'Fresh mozzarella, tomato, and basil drizzled with olive oil and balsamic glaze.',
    prepTime: 5,
    cookTime: 0,
    estimatedCost: 5.0,
    heroImage: null,
    categories: ['vegetarian', 'no-cook', 'easy'],
    ingredients: ['mozzarella', 'tomato', 'basil', 'olive oil'],
  },
  {
    id: 14,
    title: 'French Onion Soup',
    description: 'Caramelized onion soup topped with a crouton and melted gruyère cheese.',
    prepTime: 10,
    cookTime: 50,
    estimatedCost: 6.0,
    heroImage: null,
    categories: ['comfort', 'vegetarian'],
    ingredients: ['onion', 'bread', 'butter', 'gruyère'],
  },
  {
    id: 15,
    title: 'Pancakes',
    description: 'Fluffy pancakes made with flour, eggs, milk, and butter. Serve with maple syrup.',
    prepTime: 5,
    cookTime: 15,
    estimatedCost: 2.5,
    heroImage: null,
    categories: ['breakfast', 'vegetarian', 'easy'],
    ingredients: ['flour', 'eggs', 'milk', 'butter'],
  },
  {
    id: 16,
    title: 'Greek Salad',
    description: 'Cucumber, tomato, red onion, olives, and feta cheese dressed in olive oil and oregano.',
    prepTime: 10,
    cookTime: 0,
    estimatedCost: 5.5,
    heroImage: null,
    categories: ['vegetarian', 'no-cook', 'healthy', 'gluten-free'],
    ingredients: ['cucumber', 'tomato', 'onion', 'olives', 'feta', 'olive oil'],
  },
  {
    id: 17,
    title: 'Tomato Basil Bruschetta',
    description: 'Toasted baguette slices topped with diced tomato, garlic, and fresh basil.',
    prepTime: 10,
    cookTime: 5,
    estimatedCost: 3.0,
    heroImage: null,
    categories: ['vegetarian', 'quick', 'easy'],
    ingredients: ['bread', 'tomato', 'garlic', 'basil', 'olive oil'],
  },
  {
    id: 18,
    title: 'Spaghetti Bolognese',
    description: 'Ground beef slow-simmered with tomato, onion, garlic, and red wine over pasta.',
    prepTime: 10,
    cookTime: 40,
    estimatedCost: 8.0,
    heroImage: null,
    categories: ['comfort', 'high-protein'],
    ingredients: ['pasta', 'beef', 'tomato', 'onion', 'garlic'],
  },
  {
    id: 19,
    title: 'Banana Oat Smoothie',
    description: 'Blended banana, rolled oats, milk, and honey for a filling breakfast drink.',
    prepTime: 5,
    cookTime: 0,
    estimatedCost: 2.0,
    heroImage: null,
    categories: ['breakfast', 'vegetarian', 'no-cook', 'quick'],
    ingredients: ['banana', 'oats', 'milk', 'honey'],
  },
  {
    id: 20,
    title: 'Baked Salmon',
    description: 'Salmon fillet baked with lemon slices, garlic, and olive oil until flaky.',
    prepTime: 5,
    cookTime: 20,
    estimatedCost: 8.5,
    heroImage: null,
    categories: ['high-protein', 'gluten-free', 'healthy', 'fish'],
    ingredients: ['salmon', 'lemon', 'garlic', 'olive oil'],
  },
  {
    id: 21,
    title: 'Cheese Quesadillas',
    description: 'Flour tortillas filled with melted cheddar cheese, grilled until crispy.',
    prepTime: 3,
    cookTime: 7,
    estimatedCost: 2.5,
    heroImage: null,
    categories: ['vegetarian', 'quick', 'easy'],
    ingredients: ['tortillas', 'cheddar', 'butter'],
  },
  {
    id: 22,
    title: 'Lentil Soup',
    description: 'Hearty red lentil soup with cumin, tomato, onion, and a squeeze of lemon.',
    prepTime: 10,
    cookTime: 30,
    estimatedCost: 3.5,
    heroImage: null,
    categories: ['vegan', 'budget-friendly', 'healthy', 'gluten-free'],
    ingredients: ['lentils', 'cumin', 'tomato', 'onion', 'lemon'],
  },
  {
    id: 23,
    title: 'Caesar Salad',
    description: 'Romaine lettuce with parmesan, croutons, and classic Caesar dressing.',
    prepTime: 10,
    cookTime: 0,
    estimatedCost: 5.0,
    heroImage: null,
    categories: ['vegetarian', 'no-cook', 'easy'],
    ingredients: ['romaine lettuce', 'parmesan', 'bread', 'eggs'],
  },
  {
    id: 24,
    title: 'Beef Tacos',
    description: 'Ground beef seasoned with cumin and chili powder in corn tortillas with toppings.',
    prepTime: 10,
    cookTime: 15,
    estimatedCost: 7.0,
    heroImage: null,
    categories: ['quick', 'high-protein'],
    ingredients: ['beef', 'tortillas', 'cumin', 'onion', 'tomato'],
  },
  {
    id: 25,
    title: 'Mushroom Risotto',
    description: 'Creamy arborio rice cooked with mushrooms, white wine, garlic, and parmesan.',
    prepTime: 10,
    cookTime: 35,
    estimatedCost: 7.5,
    heroImage: null,
    categories: ['vegetarian', 'comfort'],
    ingredients: ['rice', 'mushrooms', 'garlic', 'parmesan', 'butter'],
  },
]

export default fakeRecipes
