/*# The following Unit test has been generated by Claude.
#Prompt: given [frontend\src\components\Homepage\Homepage.tsx], create a unit test file, testing all components
# I, Anais Perron reviewed, modified, and tested the code to ensure correctness.
*/
import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest';
import { render, screen } from '@testing-library/react';
import Homepage from './Homepage';

// ── GSAP / animation mocks ───────────────────────────────────────────────────
vi.mock('gsap', () => import('../../test/gsapMock'));
vi.mock('gsap/ScrollTrigger', () => ({ ScrollTrigger: { refresh: vi.fn() } }));
vi.mock('@gsap/react', () => ({ useGSAP: (fn: () => void) => fn() }));
vi.mock('gsap/SplitText',     () => ({ SplitText: class { chars = []; } }));
vi.mock('gsap/InertiaPlugin', () => ({ InertiaPlugin: {} }));

// ── Asset mocks ───────────────────────────────────────────────────────────────
vi.mock('../../assets/uploads/mandala.png',    () => ({ default: 'mandala.png' }));
vi.mock('../../assets/uploads/tacos.png',      () => ({ default: 'tacos.png' }));
vi.mock('../../assets/uploads/round-plate.png',() => ({ default: 'round-plate.png' }));
vi.mock('../../assets/uploads/chopsticks.png', () => ({ default: 'chopsticks.png' }));
vi.mock('../../assets/uploads/olives.png',     () => ({ default: 'olives.png' }));
vi.mock('../../assets/uploads/mint.png',       () => ({ default: 'mint.png' }));
vi.mock('../../assets/uploads/tomato.png',     () => ({ default: 'tomato.png' }));

// ── Fetch mock ────────────────────────────────────────────────────────────────
const mockRecipes = [
  { id: 1, title: 'Pasta', description: 'Italian', prepTime: 10, cookTime: 20,
    estimatedCost: 8, heroImage: null, categories: ['Italian'] },
  { id: 2, title: 'Sushi', description: 'Japanese', prepTime: 15, cookTime: 5,
    estimatedCost: 12, heroImage: null, categories: ['Japanese'] },
];

beforeEach(() => {
  Object.defineProperty(globalThis, 'scrollTo', { value: vi.fn(), writable: true });
  globalThis.fetch = vi.fn().mockResolvedValue({
    ok: true,
    json: async () => mockRecipes,
  }) as unknown as typeof fetch;
});

afterEach(() => { vi.restoreAllMocks(); });

// ─────────────────────────────────────────────────────────────────────────────

describe('Homepage — not logged in', () => {
  it('renders the .homepage root element', () => {
    render(<Homepage isLoggedIn={false} userEmail={null} />);
    expect(document.querySelector('.homepage')).toBeInTheDocument();
  });

  it('shows the zigzag features section title', () => {
    render(<Homepage isLoggedIn={false} userEmail={null} />);
    expect(screen.getByText(/our features/i)).toBeInTheDocument();
  });

  it('renders all four feature cards', () => {
    render(<Homepage isLoggedIn={false} userEmail={null} />);
    expect(screen.getByText(/plan your week/i)).toBeInTheDocument();
    expect(screen.getByText(/create your recipes/i)).toBeInTheDocument();
    expect(screen.getByText(/generate recipes/i)).toBeInTheDocument();
    expect(screen.getByText(/figure out what to cook/i)).toBeInTheDocument();
  });



  it('shows "Register now!" hero button', () => {
    render(<Homepage isLoggedIn={false} userEmail={null} />);
    expect(screen.getByRole('link', { name: /register now/i })).toBeInTheDocument();
  });


});

describe('Homepage — logged in', () => {
  it('shows the "Welcome Back" greeting in the hero (hero-welcome element)', () => {
    render(<Homepage isLoggedIn={true} userEmail="user@test.com" />);
    // Hero renders it in .hero-welcome; UserSection also renders a welcome line —
    // target the hero element directly.
    const heroWelcome = document.querySelector('.hero-welcome');
    expect(heroWelcome).toBeInTheDocument();
    expect(heroWelcome?.textContent).toMatch(/welcome back/i);
  });

  it('does not show the Register button', () => {
    render(<Homepage isLoggedIn={true} userEmail="user@test.com" />);
    expect(screen.queryByRole('link', { name: /register now/i })).not.toBeInTheDocument();
  });

  it('renders the homepage root element when logged in', () => {
    render(<Homepage isLoggedIn={true} userEmail="user@test.com" />);
    expect(document.querySelector('.homepage')).toBeInTheDocument();
  });
});

describe('Homepage — recipe API failure', () => {
  it('renders without crashing when fetch fails', async () => {
    globalThis.fetch.mockRejectedValueOnce(new Error('network error'));
    render(<Homepage isLoggedIn={true} userEmail="user@test.com" />);
    expect(document.querySelector('.homepage')).toBeInTheDocument();
  });
});
